name: AvalonCore
version: '${project.version}'
main: net.avalondevs.avaloncore.Main
api-version: 1.16
authors: [ AvalonDevs ]

commands:
  tags:
  freeze:
    description: 'target player is unable to move'
    usage: /<command> [player]
  vanish:
    description: Hides you from all normal players.
    usage: /<command>
    aliases: ["v"]
  gamemode:
    description: changes your gamemode.
    usage: /<command> [c/s/sp]
    aliases: ["gm"]